vich_uploader:
    db_driver: orm

    mappings:
       uploadedFiles:
           uri_prefix: /files/songs
           upload_destination: '%kernel.project_dir%/public/files/songs/'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
